// Code generated by MockGen. DO NOT EDIT.
// Source: strategy.go

// Package pwdcrypt is a generated GoMock package.
package pwdcrypt

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockService) Hash(pwd string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", pwd)
	ret0, _ := ret[0].(string)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockServiceMockRecorder) Hash(pwd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockService)(nil).Hash), pwd)
}

// Match mocks base method.
func (m *MockService) Match(hashed, pwd string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", hashed, pwd)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Match indicates an expected call of Match.
func (mr *MockServiceMockRecorder) Match(hashed, pwd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockService)(nil).Match), hashed, pwd)
}
